const browserGlobals = Object.fromEntries(
  [
    "window",
    "document",
    "navigator",
    "location",
    "history",
    "console",
    "performance",
    "requestAnimationFrame",
    "cancelAnimationFrame",
    "setTimeout",
    "clearTimeout",
    "setInterval",
    "clearInterval",
    "IntersectionObserver",
    "ResizeObserver",
    "MutationObserver",
    "matchMedia",
    "Image",
    "HTMLElement",
    "HTMLDialogElement",
    "HTMLCanvasElement",
    "CustomEvent",
    "Event",
    "AbortController",
    "URL",
    "URLSearchParams",
    "getComputedStyle",
    "fetch",
    "self",
  ].map((name) => [name, "readonly"]),
);

export default [
  {
    ignores: [
      "assets/**",
      "dist/**",
      "node_modules/**",
      "test-results/**",
      "playwright-report/**",
      "**/.tmp*/**",
      "**/.tmp*",
    ],
  },
  {
    files: ["**/*.{js,mjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: browserGlobals,
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      "no-unreachable": "error",
      "no-constant-condition": "error",
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-func-assign": "error",
      "valid-typeof": "error",
      "constructor-super": "error",
      "no-this-before-super": "error",
      "use-isnan": "error",
    },
  },
  {
    files: ["tools/**", "tests/**", "*.config.js"],
    languageOptions: { globals: { process: "readonly", Buffer: "readonly" } },
  },
];
